name: bf_interpreter
description: BrainF*** Interpreter.
author: JinGyeong Jeong <jjgjoojis@gmail.com>
homepage: https://github.com/joojis/bf_interpreter.dart
dependencies:
  test:
  browser: any
environment:
  sdk: ">=1.18.1"
