name: bf_interpreter
description: BrainF*** Interpreter.
author: JinGyeong Jeong <jjgjoojis@gmail.com>
homepage: https://github.com/joojis/bf_interpreter.dart
environment:
  sdk: ">=1.19.1"
dependencies:
  test:
  angular2: 2.0.0-beta.21
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
