name: bf_interpreter_web_frontend
description: Simple Web-frontend of BrainF*** Interpreter for Demonstration.
author: JinGyeong Jeong <jjgjoojis@gmail.com>
homepage: https://github.com/joojis/bf_interpreter.dart
environment:
  sdk: ">=1.18.1"
dependencies:
  bf_interpreter:
    path: ../
  browser: any
